Update deploy-ec2.yml

diff --git a/.github/workflows/deploy-ec2.yml b/.github/workflows/deploy-ec2.yml
--- a/.github/workflows/deploy-ec2.yml
+++ b/.github/workflows/deploy-ec2.yml
@@ -64,14 +64,14 @@ jobs:
             chmod +x devops/nginx-setup.sh
             devops/nginx-setup.sh "${{ env.PROJECT_NAME }}" "keraamzabih@gmail.com" "44.203.250.84" "craftapp" "ai" "${{ env.FRONTEND_PORT }}" "${{ env.BACKEND_PORT }}"
 
-      - name: Move nginx config with sudo
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.EC2_INSTANCE_IP }}
-          username: ubuntu
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          script: |
-            sudo nginx -t && sudo systemctl reload nginx
+      # - name: Move nginx config with sudo
+      #   uses: appleboy/ssh-action@master
+      #   with:
+      #     host: ${{ secrets.EC2_INSTANCE_IP }}
+      #     username: ubuntu
+      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
+      #     script: |
+      #       sudo nginx -t && sudo systemctl reload nginx
 
       - name: Deploy application
         uses: appleboy/ssh-action@master
@@ -96,6 +96,13 @@ jobs:
             docker system prune -f
             docker-compose up -d --build
             sleep 10
+                  if docker exec central-nginx nginx -t; then
+            docker exec central-nginx nginx -s reload
+            echo "✅ NGINX reloaded successfully"
+            else
+              echo "❌ NGINX configuration test failed"
+              exit 1
+            fi
             services=("frontend-1" "backend-1" "postgres-1")
 
             for service in "${services[@]}"; do
